
CREATE DATABASE JOGOS_DO_VALE;

USE JOGOS_DO_VALE

CREATE TABLE CLIENTE(
IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(30) UNIQUE
);

CREATE TABLE TELEFONE(
IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
TIPO ENUM('CEL','RES','COMERCIAL') NOT NULL,
NUMERO VARCHAR(15) NOT NULL,
ID_TELEFONE INT,
FOREIGN KEY(ID_TELEFONE)
REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE ENDERECO(
IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
RUA VARCHAR(50) NOT NULL,
BAIRRO VARCHAR(30) NOT NULL,
CIDADE VARCHAR(30) NOT NULL,
ESTADO CHAR(2) NOT NULL,
N_CASA VARCHAR(10) NOT NULL,
ID_ENDERECO INT,
FOREIGN KEY(ID_ENDERECO)
REFERENCES CLIENTE(IDCLIENTE)
);


CREATE TABLE PEDIDO(
IDPEDIDO INT PRIMARY KEY AUTO_INCREMENT,
JOGO VARCHAR(30) NOT NULL,
VALOR_PEDIDO FLOAT(10,2) NOT NULL,
VALOR_ENTREGA FLOAT(10,2),
DATA_ENTREGA DATE NOT NULL,
FORMA_PAGAMENTO ENUM('DINHEIRO','CARTÃO','PIX') NOT NULL,
ID_PEDIDO INT,
FOREIGN KEY(ID_PEDIDO)
REFERENCES CLIENTE(IDCLIENTE)
);


CREATE TABLE PRODUTO(
IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
NOME_JOGO VARCHAR(50) NOT NULL,
CATEGORIA VARCHAR(30) NOT NULL,
QNTD_ESTOQUE VARCHAR(10),
PRECO_CUSTO FLOAT(10,2) NOT NULL,
PRECO_VENDA FLOAT(10,2) NOT NULL,
LUCRO FLOAT(10,2) NOT NULL
);





